# Diyor Umurzakov, AIN-1-21

In [3]:
import numpy as np

my_arr = np.arange(0, 101, 5)
my_arr2 = my_arr[my_arr % 10 == 0]
my_arr2

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [4]:
two_arr = np.column_stack((my_arr2, my_arr2))
two_arr

array([[  0,   0],
       [ 10,  10],
       [ 20,  20],
       [ 30,  30],
       [ 40,  40],
       [ 50,  50],
       [ 60,  60],
       [ 70,  70],
       [ 80,  80],
       [ 90,  90],
       [100, 100]])

In [5]:
my_second_arr = my_arr2 - 5
my_second_arr

array([-5,  5, 15, 25, 35, 45, 55, 65, 75, 85, 95])

In [6]:
combined = np.column_stack((two_arr, my_second_arr)).T
combined

array([[  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100],
       [ -5,   5,  15,  25,  35,  45,  55,  65,  75,  85,  95]])

In [7]:
result = two_arr.copy().astype(float) 
my_array_nonzero = np.where(my_arr[:2] != 0, my_arr[:2], np.nan) 
result[0] = two_arr[0] / my_array_nonzero
my_array_nonzero = np.where(my_arr[2:4] != 0, my_arr[2:4], np.nan)
result[1] = two_arr[1] / my_array_nonzero

unchanged_mask = (result == two_arr)
result[~unchanged_mask] = np.nan
result

array([[ nan,   0.],
       [ nan,  nan],
       [ 20.,  20.],
       [ 30.,  30.],
       [ 40.,  40.],
       [ 50.,  50.],
       [ 60.,  60.],
       [ 70.,  70.],
       [ 80.,  80.],
       [ 90.,  90.],
       [100., 100.]])

In [8]:
result[[0, 2]] = result[[2, 0]]
result

array([[ 20.,  20.],
       [ nan,  nan],
       [ nan,   0.],
       [ 30.,  30.],
       [ 40.,  40.],
       [ 50.,  50.],
       [ 60.,  60.],
       [ 70.,  70.],
       [ 80.,  80.],
       [ 90.,  90.],
       [100., 100.]])

In [9]:
mean_values = np.mean(result, axis=1)
median_values = np.median(result, axis=1)
std_deviation = np.std(result, axis=1)
print(mean_values)
print(median_values)
print(std_deviation)

[ 20.  nan  nan  30.  40.  50.  60.  70.  80.  90. 100.]
[ 20.  nan  nan  30.  40.  50.  60.  70.  80.  90. 100.]
[ 0. nan nan  0.  0.  0.  0.  0.  0.  0.  0.]


In [10]:
max_values = np.max(result, axis=1)  
normalized_result = result / max_values[:, np.newaxis]
normalized_result

array([[ 1.,  1.],
       [nan, nan],
       [nan, nan],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [11]:
import pandas as pd
df = pd.read_csv("Global Population Trends(2016-2022).csv")

In [12]:
df.head()

Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0                  49.4           -  
1                  47.8         3.0  
2                  46.3         3.0  
3                  44.8         3.0  
4                  43.4         3.0

In [13]:
df.shape

(1073, 12)

In [14]:
df.columns

Index(['Country', 'Year', 'Total Population', 'Urban Population',
       'Rural Population', 'Population Density', 'Life Expectancy',
       'Birth Rate', 'Death Rate', 'Fertility Rate', 'Infant Mortality Rate',
       'Growth Rate'],
      dtype='object')

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1073 entries, 0 to 1072
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   Country                1073 non-null   object 
 1   Year                   1073 non-null   int64  
 2   Total Population       1073 non-null   object 
 3   Urban Population       1073 non-null   object 
 4   Rural Population       1073 non-null   object 
 5   Population Density     1073 non-null   object 
 6   Life Expectancy        1073 non-null   object 
 7   Birth Rate             1073 non-null   float64
 8   Death Rate             1073 non-null   float64
 9   Fertility Rate         1073 non-null   object 
 10  Infant Mortality Rate  1073 non-null   object 
 11  Growth Rate            1073 non-null   object 
dtypes: float64(2), int64(1), object(9)
memory usage: 100.7+ KB


In [16]:
df1 = df[df['Total Population'] != '-']
df1

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
6                   105            79.0      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -            61.0      34.511       6.973   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
6              1.44                   8.3         0.0  
...             ...                   ...         ...  
1067          4.308                  40.2         3.0  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[864 rows x 12 columns]

In [17]:
df1.describe()

Year  Birth Rate  Death Rate
count   864.000000  864.000000  864.000000
mean   2019.500000   18.548384    7.889123
std       1.118682    9.887518    3.041385
min    2018.000000    0.000000    0.000000
25%    2018.750000   10.500000    6.116500
50%    2019.500000   15.628500    7.453500
75%    2020.250000   25.565000    9.385000
max    2021.000000   46.127000   21.700000

In [22]:
sorted_country = df1.sort_values(by="Country")
sorted_year = df1.sort_values(by="Year")
combined_sorted = df1.sort_values(by=["Country", "Year"])
combined_sorted

Country  Year Total Population Urban Population Rural Population  \
1     Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2     Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3     Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4     Afghanistan  2021       40,099,462       10,551,772       29,547,690   
6         Albania  2018        2,866,376        1,728,969        1,137,407   
...           ...   ...              ...              ...              ...   
1067       Zambia  2021       19,473,125        8,800,295       10,672,830   
1069     Zimbabwe  2018       15,052,184        4,848,158       10,204,026   
1070     Zimbabwe  2019       15,354,608        4,945,719       10,408,889   
1071     Zimbabwe  2020       15,669,666        5,052,214       10,617,452   
1072     Zimbabwe  2021       15,993,524        5,166,388       10,827,136   

     Population Density Life Expectancy  Birth Rate  Death Rate  \
1                    56            63.0      36.927       6.981   
2                    58            64.0      36.466       6.791   
3                    60            63.0      36.051       7.113   
4                     -            62.0      35.842       7.344   
6                   105            79.0      10.517       8.308   
...                 ...             ...         ...         ...   
1067                  -            61.0      34.511       6.973   
1069                 39            61.0      32.074       7.972   
1070                 40            61.0      31.518       8.043   
1071                 41            61.0      31.009       8.132   
1072                  -            59.0      30.537       9.057   

     Fertility Rate Infant Mortality Rate Growth Rate  
1             5.002                  47.8         3.0  
2              4.87                  46.3         3.0  
3              4.75                  44.8         3.0  
4             4.643                  43.4         3.0  
6              1.44                   8.3         0.0  
...             ...                   ...         ...  
1067          4.308                  40.2         3.0  
1069          3.659                  38.0         2.0  
1070          3.599                  37.1         2.0  
1071          3.545                  36.6         2.0  
1072          3.491                  35.7         2.0  

[864 rows x 12 columns]

In [23]:
sorted_country.to_excel("sorted_by_country.xlsx")
sorted_country.to_excel("sorted_by_year.xlsx")
combined_sorted.to_excel("combined.xlsx")